on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE: docker.pkg.github.com/${{ github.repository }}/ghost-images

    steps:
      - run: docker pull alpine

      - run: docker tag alpine ${{ env.IMAGE }}

      - run: docker login https://docker.pkg.github.com -u token -p ${{ secrets.WRITE_PACKAGES_TOKEN }}

      - run: docker publish ${{ env.IMAGE }}
